version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: auditronai
      POSTGRES_PASSWORD: auditronai
      POSTGRES_DB: auditronai
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auditronai"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auditron-network

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auditron-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://auditronai:auditronai@db/auditronai
      REDIS_URL: redis://redis:6379/0
      DEBUG: "true"
      CORS_ORIGINS: '["http://localhost:3000"]'
      SECRET_KEY: "your-secret-key-here"
      POSTGRES_SERVER: "db"
      POSTGRES_USER: "auditronai"
      POSTGRES_PASSWORD: "auditronai"
      POSTGRES_DB: "auditronai"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - auditron-network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - auditron-network

networks:
  auditron-network:
    driver: bridge

volumes:
  postgres_data:
