version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      target: development
    volumes:
      - ./backend:/app
      - backend_venv:/app/venv
    environment:
      - PYTHONPATH=/app
      - WATCHFILES_FORCE_POLLING=true
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 --reload-dir /app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start
    ports:
      - "3000:3000"

  postgres:
    extends:
      file: docker-compose.local.yml
      service: postgres

  redis:
    extends:
      file: docker-compose.local.yml
      service: redis

volumes:
  backend_venv: 