apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: auditronai-jaeger
  namespace: tracing
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
        username: elastic
        password: ${ES_PASSWORD}
  ingress:
    enabled: true
    hosts:
      - jaeger.auditronai.com
    tls:
      - secretName: jaeger-tls
        hosts:
          - jaeger.auditronai.com
  agent:
    strategy: DaemonSet
  collector:
    replicas: 2
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
  query:
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi 