apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-test
  namespace: auditronai
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - auditronai
    labelSelectors:
      app: backend
  scheduler:
    cron: "@every 10m" 