apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: auditronai
spec:
  schedule: "0 1 * * *"  # Tous les jours à 1h du matin
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:13
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -F c -f /backup/db_$(date +%Y%m%d_%H%M%S).dump
              aws s3 cp /backup/db_*.dump s3://auditronai-backups/
              rm /backup/db_*.dump
            env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            emptyDir: {}
          restartPolicy: OnFailure 