apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  config.hcl: |
    path "secret/data/auditronai/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    path "auth/kubernetes/role/auditronai" {
      capabilities = ["create", "read", "update", "delete"]
    }

    path "sys/auth" {
      capabilities = ["read"]
    }

    path "sys/policies/acl" {
      capabilities = ["list"]
    }

    path "sys/policies/acl/auditronai" {
      capabilities = ["create", "read", "update", "delete"]
    } 