# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auditronai-sa
  namespace: auditronai
---
# Role pour les opérations de base
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auditronai-role
  namespace: auditronai
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create"]
---
# RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auditronai-rolebinding
  namespace: auditronai
subjects:
- kind: ServiceAccount
  name: auditronai-sa
  namespace: auditronai
roleRef:
  kind: Role
  name: auditronai-role
  apiGroup: rbac.authorization.k8s.io 